main/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from apps.reclamo.urls_api import router as router_reclamo
from setup.urls_api import router as router_setup

urlpatterns = [
                  path('', include('apps.index.url')),
                  path('accounts/', include('django.contrib.auth.urls')),
                  path('manager/', admin.site.urls),
                      #path('clearcache/', include('clearcache.urls')),


                  path('localizations/country/', include('apps.localizations.urls.country')),
                  path('localizations/department/', include('apps.localizations.urls.department')),
                  path('localizations/province/', include('apps.localizations.urls.province')),
                  path('localizations/district/', include('apps.localizations.urls.district')),

                  path('reclamo/', include('apps.reclamo.url')),
                  path('setup/usuario/', include('setup.urls.usuario')),
                  path('setup/entidad/', include('setup.urls.entidad')),
                  path('administrador/', include('apps.reclamo_administrador.url')),
                  path('evaluacion/', include('apps.evaluacion_entidad.urls')),
                  path('reportes/', include('apps.reportes.urls')),
                  path('trama-txt/', include('apps.trama_txt.urls')),

                  path('api/entidad/', include(router_reclamo.urls)),
                  path('api/setup/', include(router_setup.urls)),

              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL,
                                                                                           document_root=settings.MEDIA_ROOT)

apps/localizations/models/country.py
from django.db import models
from django.utils.translation import gettext_lazy as _


class Country(models.Model):
    code = models.CharField(_('Código'), max_length=5)
    name = models.CharField(_('Nombre'), max_length=250)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = _('País')
        verbose_name_plural = _('Países')

apps/localizations/models/department.py
from django.db import models

from apps.localizations.models.country import Country


class Department(models.Model):
    code = models.CharField(max_length=5)
    name = models.CharField(max_length=250)
    country = models.ForeignKey(Country, related_name='departments', on_delete=models.CASCADE)

    def __str__(self):
        return self.name

apps/localizations/models/district.py
from django.db import models

from apps.localizations.models.province import Province


class District(models.Model):
    code = models.CharField(max_length=6)
    name = models.CharField(max_length=150)
    longitude = models.CharField(max_length=20, null=True, blank=True)
    latitude = models.CharField(max_length=20, null=True, blank=True)
    province = models.ForeignKey(Province, related_name='districts', on_delete=models.CASCADE)

    def __str__(self):
        return self.name


    def get_full_name(self):
        return "%s - %s - %s" % (
            self.province.department.name, self.province.name, self.name)

apps/localizations/models/province.py
# -*- coding: utf-8 -*-
from django.db import models

from apps.localizations.models.department import Department


class Province(models.Model):
    code = models.CharField(max_length=5)
    name = models.CharField(max_length=150)
    department = models.ForeignKey(Department, related_name='provinces', on_delete=models.CASCADE)

    def __str__(self):
        return self.name

apps/localizations/forms/country.py
from django import forms

from apps.localizations.models.country import Country
from apps.util.generic_filters import forms as gf


class CountryForm(forms.ModelForm):
    class Meta:
        model = Country
        fields = '__all__'


class CountryListFilter(gf.FilteredForm):

    def get_order_by_choices(self):
        return []

apps/localizations/forms/department.py
from django import forms

from apps.localizations.models.department import Department
from apps.util.generic_filters import forms as gf


class DepartmentForm(forms.ModelForm):
    class Meta:
        model = Department
        fields = '__all__'


class DepartmentListFilter(gf.FilteredForm):

    def get_order_by_choices(self):
        return []

apps/localizations/forms/district.py
from django import forms

from apps.localizations.models.district import District
from apps.util.generic_filters import forms as gf


class DistrictForm(forms.ModelForm):
    class Meta:
        model = District
        fields = '__all__'


class DistrictListFilter(gf.FilteredForm):

    def get_order_by_choices(self):
        return []

apps/localizations/forms/province.py
from django import forms

from apps.localizations.models.province import Province
from apps.util.generic_filters import forms as gf


class ProvinceForm(forms.ModelForm):
    class Meta:
        model = Province
        fields = '__all__'


class ProvinceListFilter(gf.FilteredForm):

    def get_order_by_choices(self):
        return []

apps/localizations/views/country.py
from django.contrib import messages
from django.urls import reverse_lazy
from django.views.generic import CreateView, UpdateView

from apps.localizations.forms.country import CountryForm, CountryListFilter
from apps.localizations.models.country import Country
from apps.util.generic_filters.views import FilteredListView
from apps.util.views.dropdown_list import dropdown_list


class CountryList(FilteredListView):
    model = Country
    paginate_by = 10
    form_class = CountryListFilter
    filter_fields = []
    search_fields = ['name']
    default_order = '-id'

    def get_context_data(self, **kwargs):
        title = "Todas los paises"
        return dict(
            super(CountryList, self).get_context_data(**kwargs), title=title)


class CountryCreate(CreateView):
    model = Country
    form_class = CountryForm
    success_url = reverse_lazy('country:list')

    def form_valid(self, form):
        msg = "El país <strong>" + str(self.request.POST['name']) + "</strong>  fue creado correctamente."
        messages.add_message(self.request, messages.SUCCESS, msg)
        return super().form_valid(form)


class CountryUpdate(UpdateView):
    model = Country
    form_class = CountryForm
    success_url = reverse_lazy('country:list')

    def form_valid(self, form):
        msg = "El país <strong>" + str(self.request.POST['name']) + "</strong>  fue editado correctamente."
        messages.add_message(self.request, messages.SUCCESS, msg)
        return super().form_valid(form)


def dropdown_country(request):
    country_list = Country.objects.all()
    return dropdown_list(request=request, list=country_list)

apps/localizations/views/department.py
from django.urls import reverse_lazy
from django.views.generic import CreateView, UpdateView

from apps.localizations.forms.department import DepartmentForm, DepartmentListFilter
from apps.localizations.models.country import Country
from apps.localizations.models.department import Department
from apps.util.generic_filters.views import FilteredListView
from apps.util.views.dropdown_list import dropdown_list


class DepartmentList(FilteredListView):
    model = Department
    paginate_by = 10
    form_class = DepartmentListFilter
    filter_fields = []
    search_fields = ['name']
    default_order = '-id'

    def get_context_data(self, **kwargs):
        country = Country.objects.get(pk=self.kwargs['country_id'])
        title = "Lista de Departamentos del " + country.name + "."

        return dict(
            super(DepartmentList, self).get_context_data(**kwargs), title=title, country=country)

    def get_queryset(self):
        return Department.objects.filter(country_id=self.kwargs['country_id'])


class DepartmentCreate(CreateView):
    model = Department
    form_class = DepartmentForm

    def get_context_data(self, **kwargs):
        country = Country.objects.get(pk=self.kwargs['country_id'])
        title = "Agregar departamento"

        return dict(
            super(DepartmentCreate, self).get_context_data(**kwargs), title=title, country=country)

    def get_success_url(self):
        return reverse_lazy('country:department-list', kwargs={'country_id': self.kwargs['country_id']})


class DepartmentUpdate(UpdateView):
    model = Department
    form_class = DepartmentForm

    def get_context_data(self, **kwargs):
        country = Country.objects.get(pk=self.kwargs['country_id'])
        title = "Editar departamento"

        return dict(
            super(DepartmentUpdate, self).get_context_data(**kwargs), title=title, country=country)

    def get_success_url(self):
        return reverse_lazy('country:department-list', kwargs={'country_id': self.kwargs['country_id']})


def dropdown_department(request):
    department_list = []
    if request.GET.get('country_id'):
        department_list = Department.objects.filter(country_id=request.GET.get('country_id'))
    return dropdown_list(request=request, list=department_list)

apps/localizations/views/district.py
import json

from django.http.response import HttpResponse
from django.urls.base import reverse_lazy
from django.views.generic.edit import CreateView, UpdateView

from apps.localizations.forms.district import DistrictForm, DistrictListFilter
from apps.localizations.models.district import District
from apps.localizations.models.province import Province
from apps.util.generic_filters.views import FilteredListView
from apps.util.views.dropdown_list import dropdown_list


class DistrictList(FilteredListView):
    model = District
    paginate_by = 10
    form_class = DistrictListFilter
    filter_fields = []
    search_fields = ['name']
    default_order = '-id'

    def get_context_data(self, **kwargs):
        province = Province.objects.get(pk=self.kwargs['province_id'])
        title = "Lista de Distritos de la Provincia de  " + province.name + "."

        return dict(
            super(DistrictList, self).get_context_data(**kwargs), title=title, country=province.department.country,
            department=province.department, province=province)

    def get_queryset(self):
        return District.objects.filter(province_id=self.kwargs['province_id'])


class DistrictCreate(CreateView):
    model = District
    form_class = DistrictForm

    def get_context_data(self, **kwargs):
        province = Province.objects.get(pk=self.kwargs['province_id'])
        title = "Nuevo Distrito de la Provincia de " + province.name + "."

        return dict(
            super(DistrictCreate, self).get_context_data(**kwargs), title=title, country=province.department.country,
            department=province.department, province=province)

    def get_success_url(self):
        return reverse_lazy('province:district-list', kwargs={'province_id': self.kwargs['province_id']})


class DistrictUpdate(UpdateView):
    model = District
    form_class = DistrictForm

    def get_context_data(self, **kwargs):
        province = Province.objects.get(pk=self.kwargs['province_id'])
        title = "Editar Distrito de la Provincia de " + province.name + "."

        return dict(
            super(DistrictUpdate, self).get_context_data(**kwargs), title=title, country=province.department.country,
            department=province.department, province=province)

    def get_success_url(self):
        return reverse_lazy('province:district-list', kwargs={'province_id': self.kwargs['province_id']})


def dropdown_district(request):
    district_list = []
    if request.GET.get('province_id'):
        district_list = District.objects.filter(province_id=request.GET.get('province_id'))
    return dropdown_list(request=request, list=district_list)


def district_serializer(object):
    return {'id': object.id, 'name': object.name, "province_id": object.province.id,
            "province_name": object.province.name, "department_id": object.province.department.id,
            "department_name": object.province.department.name,
            "country_id": object.province.department.country.id,
            "country_name": object.province.department.country.name}


def get_district_by_id(request, pk):
    return HttpResponse(json.dumps(district_serializer(District.objects.get(pk=pk))), content_type='application/json')


from django.db.models import Q


def district_serializer_autocomplete(object):
    return {'id': object.id,
            'value': "Departamento (" + object.province.department.name + ")   |   Provincia (" + object.province.name + ")   |   Distrito (" + object.name + ")"}


def get_district_autocomplete(request):
    query = request.GET.get('term', '0')

    district_list = District.objects.filter(Q(name__icontains=query)).order_by('name')[:8]
    list_json = [district_serializer_autocomplete(district) for district in district_list]

    return HttpResponse(json.dumps(list_json),
                        content_type='application/json')

apps/localizations/views/province.py
from django.urls import reverse_lazy
from django.views.generic import CreateView, UpdateView

from apps.localizations.forms.province import ProvinceForm, ProvinceListFilter
from apps.localizations.models.department import Department
from apps.localizations.models.province import Province
from apps.util.generic_filters.views import FilteredListView
from apps.util.views.dropdown_list import dropdown_list


class ProvinceList(FilteredListView):
    model = Province
    paginate_by = 10
    form_class = ProvinceListFilter
    filter_fields = []
    search_fields = ['name']
    default_order = '-id'

    def get_context_data(self, **kwargs):
        department = Department.objects.get(pk=self.kwargs['department_id'])
        title = "Lista de Provincias del Departamento de " + department.name + "."

        return dict(
            super(ProvinceList, self).get_context_data(**kwargs), title=title, country=department.country,
            department=department)

    def get_queryset(self):
        return Province.objects.filter(department_id=self.kwargs['department_id'])


class ProvinceCreate(CreateView):
    model = Province
    form_class = ProvinceForm

    def get_context_data(self, **kwargs):
        department = Department.objects.get(pk=self.kwargs['department_id'])
        title = "Nueva provincia"

        return dict(
            super(ProvinceCreate, self).get_context_data(**kwargs), title=title, country=department.country,
            department=department)

    def get_success_url(self):
        return reverse_lazy('department:province-list', kwargs={'department_id': self.kwargs['department_id']})


class ProvinceUpdate(UpdateView):
    model = Province
    form_class = ProvinceForm

    def get_context_data(self, **kwargs):
        department = Department.objects.get(pk=self.kwargs['department_id'])
        title = "Editar provincia"

        return dict(
            super(ProvinceUpdate, self).get_context_data(**kwargs), title=title, country=department.country,
            department=department)

    def get_success_url(self):
        return reverse_lazy('department:province-list', kwargs={'department_id': self.kwargs['department_id']})


def dropdown_province(request):
    province_list = []
    if request.GET.get('department_id'):
        province_list = Province.objects.filter(department_id=request.GET.get('department_id'))
    return dropdown_list(request=request, list=province_list)

apps/localizations/templates/localizations/country_form.html
{% extends 'dashboard.html' %}
{% block  container %}

    <div class="app-content content">
        <div class="content-wrapper">
            <div class="content-header row">
                <div class="content-header-left col-md-6 col-12 mb-2">
                    <div class="row breadcrumbs-top">
                        <div class="breadcrumb-wrapper col-12">
                            <ol class="breadcrumb">
                                <li class="breadcrumb-item active">Localización</li>
                                <li class="breadcrumb-item active">Paises</li>
                                <li class="breadcrumb-item ">
                                    <a href="{% url 'country:list' %}">Todos los paises</a></li>
                                <li class="breadcrumb-item active">{{ title }}</li>
                            </ol>
                        </div>
                    </div>
                </div>
            </div>

            <div class="content-body">
                <section id="patients-list">
                    <div class="row">
                        <div class="col-12">
                            <div class="card">
                                <div class="card-header">
                                    <h2 class="card-title">{{ title }}</h2>
                                </div>
                                <div class="card-body collapse show">
                                    <form id="father-form" class="text-left was-validated form-validate" method="POST">
                                        {% csrf_token %}
                                        <div class="form-row">
                                            {% include 'includes/bs4_form.html' with form=form col=4 exclude=" " start_tabindex=0 hidden=" " %}
                                        </div>
                                        <div class="form-group">
                                            <div class="text-right">
                                                <a type="" href="{% url 'country:list' %}"
                                                   class="btn  btn-danger form-button">Cancelar</a>
                                                <button type="submit" class="btn btn-success form-button">Guardar
                                                </button>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </section>
            </div>
        </div>
    </div>

{% endblock container %}

{% block static %}

{% endblock static %}

apps/localizations/templates/localizations/department_form.html
{% extends 'dashboard.html' %}
{% block  container %}
    <div class="app-content content">
        <div class="content-wrapper">
            <div class="content-header row">
                <div class="content-header-left col-md-12 col-12 mb-2">
                    <div class="row breadcrumbs-top">
                        <div class="breadcrumb-wrapper col-12">
                            <ol class="breadcrumb">
                                <li class="breadcrumb-item active">Localización</li>
                                <li class="breadcrumb-item active">Paises</li>
                                <li class="breadcrumb-item ">
                                    <a href="{% url 'country:list' %}">Todos los paises</a></li>
                                <li class="breadcrumb-item ">
                                    <a href="{% url  'country:department-list' country_id=country.id %}">Lista de
                                        departamentos del {{ country.name }}</a></li>
                                <li class="breadcrumb-item active">{{ title }}</li>
                            </ol>
                        </div>
                    </div>
                </div>
            </div>

            <div class="content-body">
                <section id="patients-list">
                    <div class="row">
                        <div class="col-12">
                            <div class="card">
                                <div class="card-header">
                                    <h2 class="card-title">{{ title }}</h2>
                                </div>
                                <div class="card-body collapse show">
                                    <form id="father-form" class="text-left was-validated form-validate" method="POST">
                                        {% csrf_token %}
                                        <div class="form-row">
                                            {% include 'includes/bs4_form.html' with form=form col=4 exclude=" " start_tabindex=0 hidden="country " %}
                                        </div>
                                        <div class="form-group">
                                            <div class="text-right">
                                                <a href="{% url  'country:department-list' country_id=country.id %}"
                                                   class="btn  btn-danger form-button">Cancelar</a>
                                                <button type="submit" class="btn btn-success form-button">Guardar
                                                </button>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </section>
            </div>
        </div>
    </div>


{% endblock container %}

{% block static %}

    <script type="application/javascript">
        $(function () {
            $("#id_country").val("{{ country.id }}")
        })
    </script>

{% endblock static %}

apps/localizations/templates/localizations/district_form.html
{% extends 'dashboard.html' %}
{% block  container %}
    <div class="app-content content">
        <div class="content-wrapper">
            <div class="content-header row">
                <div class="content-header-left col-md-12 col-12 mb-2">
                    <div class="row breadcrumbs-top">
                        <div class="breadcrumb-wrapper col-12">
                            <ol class="breadcrumb">
                                <li class="breadcrumb-item active">Localización</li>
                                <li class="breadcrumb-item active">Paises</li>
                                <li class="breadcrumb-item ">
                                    <a href="{% url 'country:list' %}">Todos los paises</a></li>
                                <li class="breadcrumb-item ">
                                    <a href="{% url  'country:department-list' country_id=country.id %}">Lista de
                                        departamentos del {{ country.name }}</a></li>
                                <li class="breadcrumb-item ">
                                    <a href="{% url  'department:province-list' department_id=department.id %}"> Lista
                                        de provincias del departamento de {{ department.name }}</a></li>
                                <li class="breadcrumb-item "><a
                                        href="{% url  'province:district-list' province_id=province.id %}">
                                    Lista de distritos de la Provincia de {{ province.name }}</a></li>
                                <li class="breadcrumb-item active">{{ title }}</li>
                            </ol>
                        </div>
                    </div>
                </div>
            </div>

            <div class="content-body">
                <section id="patients-list">
                    <div class="row">
                        <div class="col-12">
                            <div class="card">
                                <div class="card-header">
                                    <h2 class="card-title">{{ title }}</h2>
                                </div>
                                <div class="card-body collapse show">
                                    <form id="father-form" class="text-left was-validated form-validate" method="POST">
                                        {% csrf_token %}
                                        <div class="form-row">
                                            {% include 'includes/bs4_form.html' with form=form col=4 exclude=" " start_tabindex=0 hidden="province " %}
                                        </div>
                                        <div class="form-group">
                                            <div class="text-right">
                                                <a href="{% url  'province:district-list' province_id=province.id %}"
                                                   class="btn  btn-danger form-button">Cancelar</a>
                                                <button type="submit" class="btn btn-success form-button">Guardar
                                                </button>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </section>
            </div>
        </div>
    </div>

{% endblock container %}

{% block static %}

    <script type="application/javascript">
        $(function () {
            $("#id_province").val("{{ province.id }}")
        })
    </script>

{% endblock static %}

apps/localizations/templates/localizations/province_form.html
{% extends 'dashboard.html' %}
{% block  container %}
    <div class="app-content content">
        <div class="content-wrapper">
            <div class="content-header row">
                <div class="content-header-left col-md-12 col-12 mb-2">
                    <div class="row breadcrumbs-top">
                        <div class="breadcrumb-wrapper col-12">
                            <ol class="breadcrumb">
                                <li class="breadcrumb-item active">Localización</li>
                                <li class="breadcrumb-item active">Paises</li>
                                <li class="breadcrumb-item ">
                                    <a href="{% url 'country:list' %}">Todos los paises</a></li>
                                <li class="breadcrumb-item ">
                                    <a href="{% url  'country:department-list' country_id=country.id %}">Lista de
                                        departamentos del {{ country.name }}</a></li>
                                <li class="breadcrumb-item ">
                                    <a href="{% url  'department:province-list' department_id=department.id %}"> Lista
                                        de provincias del departamento de {{ department.name }}</a></li>
                                <li class="breadcrumb-item active">{{ title }}</li>
                            </ol>
                        </div>
                    </div>
                </div>
            </div>

            <div class="content-body">
                <section id="patients-list">
                    <div class="row">
                        <div class="col-12">
                            <div class="card">
                                <div class="card-header">
                                    <h2 class="card-title">{{ title }}</h2>
                                </div>
                                <div class="card-body collapse show">
                                    <form id="father-form" class="text-left was-validated form-validate" method="POST">
                                        {% csrf_token %}
                                        <div class="form-row">
                                            {% include 'includes/bs4_form.html' with form=form col=4 exclude=" " start_tabindex=0 hidden="department " %}
                                        </div>
                                        <div class="form-group">
                                            <div class="text-right">
                                                <a href="{% url  'department:province-list' department_id=department.id %}"
                                                   class="btn  btn-danger form-button">Cancelar</a>
                                                <button type="submit" class="btn btn-success form-button">Guardar
                                                </button>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </section>
            </div>
        </div>
    </div>


{% endblock container %}

{% block static %}

    <script type="application/javascript">
        $(function () {
            $("#id_department").val("{{ department.id }}")
        })
    </script>

{% endblock static %}