main/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from apps.reclamo.urls_api import router as router_reclamo
from setup.urls_api import router as router_setup

urlpatterns = [
                  path('', include('apps.index.url')),
                  path('accounts/', include('django.contrib.auth.urls')),
                  path('manager/', admin.site.urls),
                      #path('clearcache/', include('clearcache.urls')),


                  path('localizations/country/', include('apps.localizations.urls.country')),
                  path('localizations/department/', include('apps.localizations.urls.department')),
                  path('localizations/province/', include('apps.localizations.urls.province')),
                  path('localizations/district/', include('apps.localizations.urls.district')),

                  path('reclamo/', include('apps.reclamo.url')),
                  path('setup/usuario/', include('setup.urls.usuario')),
                  path('setup/entidad/', include('setup.urls.entidad')),
                  path('administrador/', include('apps.reclamo_administrador.url')),
                  path('evaluacion/', include('apps.evaluacion_entidad.urls')),
                  path('reportes/', include('apps.reportes.urls')),
                  path('trama-txt/', include('apps.trama_txt.urls')),

                  path('api/entidad/', include(router_reclamo.urls)),
                  path('api/setup/', include(router_setup.urls)),

              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL,
                                                                                           document_root=settings.MEDIA_ROOT)

setup/models/auto.py
from django.db import models

class Auto(models.Model):
    id = models.AutoField(primary_key=True)
    cod_patrimonial = models.CharField(max_length=50, null=True, blank=True)
    placa = models.CharField(max_length=10, null=True, blank=True)
    clase = models.CharField(max_length=30, null=True, blank=True)
    marca = models.CharField(max_length=30, null=True, blank=True)
    modelo = models.CharField(max_length=50, null=True, blank=True)
    anio = models.CharField(max_length=4, null=True, blank=True)
    combustible = models.CharField(max_length=20, null=True, blank=True)
    estado_auto = models.IntegerField(null=True, blank=True)

    class Meta:
        db_table = 'setup_auto'   

    def __str__(self):
        # 👇 puedes personalizar lo que quieras mostrar
        return f"{self.placa} - {self.marca} {self.modelo}"

setup/models/ris.py
from django.db import models

class Ris(models.Model):
    id = models.AutoField(primary_key=True)  # campo entero autoincremental
    denominacion = models.CharField(max_length=50)
    estado = models.IntegerField(null=True, blank=True)

    class Meta:
        db_table = 'setup_ris'  # nombre de la tabla en la BD
        verbose_name = 'Rises'
        verbose_name_plural = 'Rises'

    def __str__(self):
        return self.denominacion

setup/models/usuario.py
import os
import sys

if os.path.splitext(os.path.basename(sys.argv[0]))[0] == 'pydoc-script':
    import django

    django.setup()

from datetime import date

from django.contrib.auth.models import AbstractUser
from django.core.validators import RegexValidator
from django.db import models
from django.utils.translation import gettext_lazy as _

from setup.models.entidad import Entidad

TYPES = (
    ('DNI', 'DNI'),
    ('PASSPORD', 'PASAPORTE'),
)

DEGRESS = (
    (0, 'SIN ESTUDIOS'),
    (1, 'PRIMARIA COMPLETA'),
    (2, 'PRIMARIA INCOMPLETA '),
    (3, 'SECUNDARIA COMPLETA'),
    (4, 'SECUNDARIA INCOMPLETA'),
    (5, 'ESTUDIOS SUPERIORES'),
)

CIVIL_STATUS = (
    (0, 'SOLTERO'),
    (1, 'CASADO'),
    (2, 'DIVORCIADO'),
    (3, 'VIUDO'),
)

SEXS = (
    (0, 'FEMENINO'),
    (1, 'MASCULINO'),
)

RIS = (
    (0, ' ----------'),
    (1, 'RIS BCO-CHO-SCO'),
    (2, 'RIS LURIN Y BALNERARIOS'),
    (3, 'RIS PACHACAMAC'),
    (4, 'RIS SJM'),
    (5, 'RIS VES'),
    (6, 'RIS VMT'),
    (7, 'DIRIS SEDE ADMINISTRATIVA'),
)


def calculate_age(born):
    today = date.today()
    return today.year - born.year - ((today.month, today.day) < (born.month, born.day))


class Usuario(AbstractUser):
    entidad = models.ForeignKey(Entidad, verbose_name='IPRESS', on_delete=models.CASCADE, null=True, blank=True)
    # document = models.CharField(_('número de DNI'), max_length=12, unique=True, validators=[
    #     RegexValidator(regex='^.{8}$', message=_('Tiene que ingresa 8 dígitos'), code='nomatch')])

    document = models.CharField(_('número de DNI'), max_length=12, null=True, blank=True)
    celular = models.IntegerField(_('número de celular'), null=True, blank=True, validators=[
        RegexValidator(regex='^.{9}$', message=_('tiene que ingresa 9 dígitos.'), code='nomatch')])

    ris = models.IntegerField(_('Administrador RIS'), choices=RIS, default=0)
    rol = models.IntegerField(_('Rol'), null=True, blank=True)

    # document = models.CharField(_('número de DNI'), max_length=12, unique=True, validators=[
    #     RegexValidator(regex='^.{8}$', message=_('Tiene que ingresa 8 dígitos'), code='nomatch')])

    # REQUIRED_FIELDS = ['entidad']

    # renipress = models.CharField(_('Renipress'), max_length=25, null=True, blank=True)

    def __str__(self):
        return self.username

    class Meta:
        verbose_name = _('Usuario')
        verbose_name_plural = _('Usuarios')

setup/forms/entidad.py
from django import forms

from apps.util.generic_filters import forms as gf
from setup.models.entidad import Entidad


class EntidadForm(forms.ModelForm):
    class Meta:
        model = Entidad
        fields = '__all__'


class EntidadListFilter(gf.FilteredForm):

    def get_order_by_choices(self):
        return []

setup/views/entidad.py
import datetime

from django.contrib import messages
from django.db.models import Count, Q
from django.shortcuts import render
from django.urls import reverse
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, UpdateView, ListView

from apps.reclamo.models.entidad_reclamo import MESES
from apps.util.anios import ANIOS
from apps.util.update_menu import update_menu
from apps.util.valid_user_access_views import valid_access_view, permission_and_entidad, \
    valid_entidad, valid_entidad_add
from setup.forms.entidad import EntidadForm
from setup.models.entidad import Entidad


class EntidadList(ListView):
    model = Entidad
    paginate_by = 30

    # form_class = EntidadListFilter
    # filter_fields = []
    # search_fields = ['nombre']
    # default_order = '-numero_reclamos'

    @method_decorator(valid_access_view(permission_and_entidad, login_url='/validate'))
    def dispatch(self, *args, **kwargs):
        return super(EntidadList, self).dispatch(*args, **kwargs)

    def get_queryset(self):
        msg = "Lista actualizada."
        messages.add_message(self.request, messages.SUCCESS, msg)

        queryset = super().get_queryset()

        if len(self.request.user.groups.filter(name="Administrador IPRESS")) > 0:
            queryset = queryset.filter(entidad_id=self.request.user.entidad.id)

        if len(self.request.user.groups.filter(name="Administrador RIS")) > 0:
            queryset = queryset.filter(ris=self.request.user.ris)

        anio = int(self.request.GET.get('anio', datetime.datetime.now().year))
        mes = int(self.request.GET.get('mes', datetime.datetime.now().month))
        query = self.request.GET.get('query', "")

        self.request.session['entidad_anio'] = anio
        self.request.session['entidad_mes'] = mes

        if query:
            queryset = queryset.filter(nombre__icontains=query)

        # return queryset.annotate(
        #     reclamos_count=Count('reclamos',
        #                          filter=Q(reclamos__fecha_reclamo__year=anio) & Q(reclamos__fecha_reclamo__month=mes),
        #                          distinct=True)
        # ).annotate(
        #     medidas_adoptadas_count=Count(
        #         'reclamos',
        #         filter=Q(reclamos__medidas_adoptadas__fecha_inicio__year=anio) &
        #                Q(reclamos__medidas_adoptadas__fecha_inicio__month=mes), distinct=True)
        # ).annotate(
        #     q q   q   q   q   q   q   q   q   q   q   q   q   q   q   q   q   q   q   q   q   q   q   q   q   q   q   q   q   q   q   q   q   q   q   q   s_count=Count(
        #         'reclamos',
        #         filter=Q(reclamos__fecha_reclamo__year=anio) & Q(reclamos__fecha_reclamo__month=mes) &
        #                ~Q(reclamos__expediente=''), distinct=True))
        #
        #

        return queryset.annotate(
            reclamos_count=Count('reclamos',
                                 filter=Q(reclamos__fecha_reclamo__year=anio) & Q(reclamos__fecha_reclamo__month=mes),
                                 distinct=True)
        ).annotate(
            medidas_adoptadas_count=Count(
                'reclamos__medidas_adoptadas',
                filter=Q(reclamos__fecha_reclamo__year=anio) &
                       Q(reclamos__fecha_reclamo__month=mes), distinct=True)
        ).annotate(
            expedientes_count=Count(
                'reclamos',
                filter=Q(reclamos__fecha_reclamo__year=anio) & Q(reclamos__fecha_reclamo__month=mes) &
                       ~Q(reclamos__expediente=''), distinct=True)
        ).annotate(
            reclamos_virtuales_count=Count(
                'reclamos',
                filter=Q(reclamos__fecha_reclamo__year=anio) & Q(reclamos__fecha_reclamo__month=mes)
                       & Q(reclamos__medio_presentacion=1) & ~Q(reclamos__servicio_hecho_reclamo=77), distinct=True)
        ).annotate(
            reclamos_virtuales_proceso_count=Count(
                'reclamos',
                filter=Q(reclamos__fecha_reclamo__year=anio) & Q(reclamos__fecha_reclamo__month=mes)
                       & Q(reclamos__medio_presentacion=1) & Q(reclamos__servicio_hecho_reclamo=77), distinct=True))

    def get_context_data(self, **kwargs):
        title = "Todas las IPRESS"
        update_menu(self.request)

        anio = int(self.request.GET.get('anio', datetime.datetime.now().year))
        mes = int(self.request.GET.get('mes', datetime.datetime.now().month))
        query = self.request.GET.get('query', "")

        return dict(
            super(EntidadList, self).get_context_data(**kwargs), title=title, anios=ANIOS, meses=MESES, anio=anio,
            mes=mes, query=query)


class EntidadCreate(CreateView):
    model = Entidad
    form_class = EntidadForm

    @method_decorator(valid_access_view(valid_entidad_add, login_url='/validate'))
    def dispatch(self, *args, **kwargs):
        return super(EntidadCreate, self).dispatch(*args, **kwargs)

    def form_valid(self, form):
        msg = "IPRESS agregada correctamente."
        messages.add_message(self.request, messages.SUCCESS, msg)
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('entidad:list', kwargs={}) + "?anio=" + \
               str(self.request.session['entidad_anio']) + "&mes=" + str(self.request.session['entidad_mes'])


class EntidadUpdate(UpdateView):
    model = Entidad
    form_class = EntidadForm

    # success_url = reverse_lazy('entidad:list')

    @method_decorator(valid_access_view(valid_entidad, login_url='/validate'))
    def dispatch(self, *args, **kwargs):
        return super(EntidadUpdate, self).dispatch(*args, **kwargs)

    def form_valid(self, form):
        msg = "IPRESS editada correctamente."
        messages.add_message(self.request, messages.SUCCESS, msg)
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('entidad:list', kwargs={}) + "?anio=" + \
               str(self.request.session['entidad_anio']) + "&mes=" + str(self.request.session['entidad_mes'])


def get_select_list_ipress(request):
    list = []
    if request.GET.get('ris_id'):
        list = Entidad.objects.filter(ris=int(request.GET.get('ris_id')))

    return render(request, 'setup/ipress_select_list.html', {'objects_list': list})

setup/views/usuario.py
import os
import sys

from setup.models.entidad import Entidad

if os.path.splitext(os.path.basename(sys.argv[0]))[0] == 'pydoc-script':
    pass

# django.setup()

from django.contrib import messages
from django.contrib.auth.models import Group
from django.urls.base import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import UpdateView
from django.views.generic.edit import CreateView

from apps.util.generic_filters.views import FilteredListView
from apps.util.valid_user_access_views import valid_access_view, permission_and_entidad
from setup.forms.usuario import UsuarioListFilter, UsuarioForm, UsuarioChangeForm, UsuarioChangePasswordForm
from setup.models.usuario import Usuario


class UsuarioList(FilteredListView):
    model = Usuario
    paginate_by = 30
    form_class = UsuarioListFilter
    search_fields = ['username', 'first_name', 'last_name', 'document','entidad__nombre']
    default_order = 'id'

    # @method_decorator(user_passes_test(is_manager_or_admin, login_url='/reclamo/entidad-reclamo/list'))
    # def dispatch(self, *args, **kwargs):
    #     return super(UsuarioList, self).dispatch(*args, **kwargs)

    @method_decorator(valid_access_view(permission_and_entidad, login_url='/validate'))
    def dispatch(self, *args, **kwargs):
        return super(UsuarioList, self).dispatch(*args, **kwargs)

    def get_context_data(self, **kwargs):
        title = "Todos los usuarios"
        return dict(
            super(UsuarioList, self).get_context_data(**kwargs), title=title)

    def get_queryset(self):
        groups = [g.id for g in Group.objects.filter(name__in=['Administrador', 'Trabajador'])]

        queryset = super().get_queryset()
        # return queryset.filter(is_staff=False).exclude(groups__in=groups).order_by('-id')
        return queryset.filter(is_staff=False).order_by('-id')


class UsuarioCreate(CreateView):
    form_class = UsuarioForm
    model = Usuario
    success_url = reverse_lazy('usuario:list')

    # @method_decorator(user_passes_test(is_manager_or_admin, login_url='/reclamo/entidad-reclamo/list'))
    # def dispatch(self, *args, **kwargs):
    #     return super(UsuarioCreate, self).dispatch(*args, **kwargs)

    def form_valid(self, form):
        self.object = form.save()
        groups = self.request.POST.getlist("groups")
        project = self.request.POST.getlist("project")

        persona = Usuario.objects.get(pk=self.object.id)

        # if project:
        #     projects = Usuario.objects.filter(id__in=project)
        #     for p in projects:
        #         persona.project.add(p)
        #         persona.save()

        if groups:
            grupos = Group.objects.filter(id__in=groups)
            for g in grupos:
                persona.groups.add(g)
                persona.save()

        msg = "El Usuario <strong>" + str(self.request.POST['username']) + "</strong>  fue agregado correctamente"
        messages.add_message(self.request, messages.SUCCESS, msg)
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        title = "Agregar Usuario"
        return dict(
            super(UsuarioCreate, self).get_context_data(**kwargs), title=title)


class UsuarioUpdate(UpdateView):
    form_class = UsuarioChangeForm
    model = Usuario
    success_url = reverse_lazy('usuario:list')

    # @method_decorator(user_passes_test(is_manager_or_admin, login_url='/reclamo/entidad-reclamo/list'))
    # def dispatch(self, *args, **kwargs):
    #     return super(UsuarioUpdate, self).dispatch(*args, **kwargs)

    def get_context_data(self, **kwargs):
        usuario = Usuario.objects.get(pk=self.kwargs['pk'])
        title = "Actualizar Usuario"
        groups = [g.name for g in usuario.groups.all()]
        return dict(
            super(UsuarioUpdate, self).get_context_data(**kwargs), usuario=usuario, title=title, groups=groups)

    def form_valid(self, form):
        msg = "El Usuario <strong>" + str(
            self.request.POST['username'] + "</strong>  fue editado correctamente")
        messages.add_message(self.request, messages.SUCCESS, msg)
        self.object = form.save(commit=False)
        grupos = self.request.POST.getlist('groups')
        groups_name = [g.name for g in Group.objects.filter(id__in=grupos)]

        self.object.entidad = None
        self.object.ris = 0

        for g in groups_name:
            if g == "Administrador RIS":
                self.object.ris = self.request.POST['ris']
            if g == "Administrador IPRESS":
                if self.request.POST['entidad']:
                    self.object.entidad = Entidad.objects.get(pk=self.request.POST['entidad'])
        self.object.save()

        return super().form_valid(form)


class UserPasswordUpdate(UpdateView):
    form_class = UsuarioChangePasswordForm
    model = Usuario
    template_name = "setup/change_password.html"

    def get_success_url(self):
        return reverse_lazy('usuario:edit',
                            kwargs={'pk': self.object.id})

    def get_context_data(self, **kwargs):
        user_object = Usuario.objects.get(pk=self.kwargs['pk'])
        title = "Actualizar contraseña"

        return dict(
            super(UserPasswordUpdate, self).get_context_data(**kwargs), user_object=user_object, title=title)

    def form_valid(self, form):
        msg = "Contraseña actualizada del usuario: <strong>" + str(
            self.request.POST['username'] + "</strong>")
        messages.add_message(self.request, messages.SUCCESS, msg)

        return super().form_valid(form)

setup/templates/setup/ipress_select_list.html
<option value="0"> -- TODO --</option>
{% for object in objects_list %}
    <option value="{{ object.pk }}">{{ object.nombre }} - {{ object.codigo }} </option>
{% endfor %}

setup/templates/setup/usuario_form.html
{% extends 'dashboard.html' %}
{% load static %}
{% block  container %}


    <link rel="stylesheet" type="text/css" href="{% static 'css/selectize.bootstrap4.css' %}">

    <div class="app-content content">
        <div class="content-wrapper">
            <div class="content-header row">
                <div class="content-header-left col-md-6 col-12 mb-2">
                    <div class="row breadcrumbs-top">
                        <div class="breadcrumb-wrapper col-12">
                            <ol class="breadcrumb">
                                <li class="breadcrumb-item active">Configuraciones</li>
                                <li class="breadcrumb-item active">Usuarios</li>
                                <li class="breadcrumb-item ">
                                    <a href="{% url 'usuario:list' %}">Todos los usuarios</a></li>
                                <li class="breadcrumb-item active">{{ title }}</li>
                            </ol>
                        </div>
                    </div>
                </div>
            </div>

            <div class="content-body">
                <section id="patients-list">
                    <div class="row">
                        <div class="col-12">
                            <div class="card">
                                <div class="card-header">
                                    <h2 class="card-title">{{ title }}</h2>
                                </div>
                                <div class="card-body collapse show">
                                    <form class="text-left was-validated form-validate" method="POST">
                                        {% csrf_token %}

                                        <div class="form-row">
                                            {% if form.instance.id %}
                                                <div class="col-md-4">
                                                    <label for="id_person-username">Contraseña:</label>
                                                    <div class="form-group">
                                                        <a href="{% url 'usuario:password' form.instance.id %}"
                                                           class="btn btn-warning ">Cambiar contraseña</a>
                                                    </div>
                                                </div>
                                                {% include 'includes/bs4_form.html' with form=form col=4 exclude='entidad ris' start_tabindex="1" hidden="last_login is_superuser  user_permissions is_staff password" multiselect="multiselect" select_type="chekbox" %}

                                                <div id="content-entidad" class="col-md-4">
                                                    {% include 'includes/bs4_form.html' with form=form col=12 exclude='' start_tabindex="1" hidden="" include="entidad" %}
                                                </div>

                                                <div id="content-ris" class="col-md-4">
                                                    {% include 'includes/bs4_form.html' with form=form col=12 exclude='' start_tabindex="1" hidden="" include="ris" %}
                                                </div>


                                            {% else %}
                                                {% include 'includes/bs4_form.html' with form=form col=4 exclude='entidad ris' start_tabindex="1" hidden="last_login is_superuser  user_permissions is_staff" multiselect="multiselect" select_type="chekbox" %}
                                                <div id="content-entidad" class="col-md-4">
                                                    {% include 'includes/bs4_form.html' with form=form col=12 exclude='' start_tabindex="1" hidden="" include="entidad" %}
                                                </div>

                                                <div id="content-ris" class="col-md-4">
                                                    {% include 'includes/bs4_form.html' with form=form col=12 exclude='' start_tabindex="1" hidden="" include="ris" %}
                                                </div>
                                            {% endif %}


                                        </div>
                                        <div class="form-group">
                                            <div class="text-right">
                                                <a type="button" href="{% url 'usuario:list' %}"
                                                   class="btn  btn-danger form-button">Cancelar</a>
                                                <button type="submit" class="btn btn-success form-button btnSubmit">
                                                    Guardar
                                                </button>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </section>
            </div>
        </div>
    </div>

{% endblock container %}

{% block static %}
    <script src="{% static 'js/selectize.js' %} "></script>
    <script src="{% static 'js/main_select.js' %} "></script>

    {% if form.instance.id %}
        {% autoescape off %}
            <script type="application/javascript">
                window.addEventListener("load", function (event) {
                    const grupos = {{ groups|safe }}
                        grupos.forEach(element => {
                            if (element === "Administrador IPRESS") {
                                $("#content-entidad").show();
                            }
                            if (element === "Administrador RIS") {
                                $("#content-ris").show();
                            }
                        });
                });
            </script>
        {% endautoescape %}

    {% endif %}

    <script type="application/javascript">

        $("#content-entidad").hide();
        $("#content-ris").hide();

        setTimeout(function () {
            $('#id_password').get(0).type = 'password';
        }, 500);

        $('#id_entidad').selectize({
            create: true,
            sortField: {
                field: 'text',
                direction: 'asc'
            },
            dropdownParent: 'body'
        });


        window.addEventListener("load", function (event) {

            $("#id_groups").change(function () {
                $("#content-entidad").hide();
                $("#content-ris").hide();
                $("#id_groups option:selected").each(function () {
                    const value = $(this).text();
                    if (value === "Administrador IPRESS") {
                        $("#content-entidad").show();
                    }
                    if (value === "Administrador RIS") {
                        $("#content-ris").show();
                    }
                });
            });
        });

    </script>





    {#    <script src="{% static 'js/jquery.min.js' %} "></script>#}



    {#        {% include 'includes/ubigeo_js.html' with form=form object=person %}#}

{% endblock static %}

setup/templates/setup/usuario_list.html
{% extends 'dashboard.html' %}
{% load paginator i18n %}
{% block  container %}

    <div class="app-content content">
        <div class="content-wrapper">
            <div class="content-header row">
                <div class="content-header-left col-md-6 col-12 mb-2">
                    <div class="row breadcrumbs-top">
                        <div class="breadcrumb-wrapper col-12">
                            <ol class="breadcrumb">
                                <li class="breadcrumb-item active">Configuraciones</li>
                                <li class="breadcrumb-item active">Usuarios</li>
                                <li class="breadcrumb-item active">{{ title }}</li>
                            </ol>
                        </div>
                    </div>
                </div>
                <div class="content-header-right col-md-6 col-12">
                    <div class=" float-md-right">
                        <div class="col-sm-12 col-lg-12 col-xl-12">
                            <a href="{% url 'usuario:new' %}" class="btn btn-success  btn-block">
                                <i class="la la-plus  font-small-2"></i>Nuevo usuario</a>
                        </div>
                    </div>
                </div>
            </div>

            <div class="content-body">
                <section id="patients-list">
                    <div class="row">
                        <div class="col-12">
                            <div class="card">
                                <div class="card-header">
                                    <h2 class="card-title">{{ title }}
                                        <strong class="text-primary">({{ page_obj.paginator.count }})</strong></h2>
                                </div>
                                <div class="card-body collapse show">
                                    <div class="row">
                                        <div class="col-md-2 " hidden>
                                            {% include 'genericfilters/filter_list.html' %}
                                        </div>
                                        <div class="col-md-12">
                                            {% trans "Nombres, Apellidos o DNI " as placeholder %}
                                            {% include 'genericfilters/query_filter.html' %}
                                            <div class="table-responsive">
                                                <div class="table-responsive">
                                                    <table class="table table-striped table-bordered patients-list">
                                                        <thead>
                                                        <tr>
                                                            <th>#</th>
                                                            <th>Nombres y Apellidos</th>
                                                            <th>Usuario</th>
                                                            <th>IPRESS</th>
                                                            <th>RIS</th>
                                                            <th>Roles</th>
                                                            <th>Opc.</th>
                                                        </tr>
                                                        </thead>
                                                        <tbody>

                                                        {% for object in object_list %}
                                                            <tr>
                                                                <th>{{ forloop.counter0|add:page_obj.start_index }}</th>
                                                                <td>{{ object.get_full_name }}</td>
                                                                <td>{{ object.username }}</td>
                                                                <td>{{ object.entidad|default_if_none:"----------" }}</td>
                                                                <td>{{ object.get_ris_display }}</td>
                                                                <td>
                                                                    {% for g in object.groups.all %}
                                                                        <span class="badge badge-info">{{ g.name }}</span>
                                                                    {% endfor %}
                                                                </td>
                                                                <td class="text-center">
                                                                    <a href="{% url 'usuario:edit' object.id %}"
                                                                       class="btn btn-warning btn-sm"
                                                                       data-toggle="tooltip" data-placement="top"
                                                                       title="Editar Usuario">
                                                                        <i class="ft ft-edit font-medium-2 "> </i>
                                                                    </a>
                                                                </th>
                                                            </tr>
                                                        {% endfor %}
                                                        </tbody>
                                                    </table>
                                                </div>
                                               <!-- paginator-->
                                            </div>
                                        </div>
                                    </div>

                                </div>
                            </div>
                        </div>
                    </div>
                </section>
            </div>
        </div>
    </div>

{% endblock container %}

{% block static %}

{% endblock static %}