apps/evaluacion_entidad/urls.py
from django.contrib.auth.decorators import login_required, user_passes_test
from django.urls import path

from apps.evaluacion_entidad.views.evalucion_anexo1 import EvaluacionEntidadAnexo1List, EvaluacionEntidadAnexo1Create, \
    EvaluacionEntidadAnexo1Update, EvaluacionEntidadAnexo1Delete

app_name = 'evaluacion-entidad'

urlpatterns = [
    path('list', login_required(EvaluacionEntidadAnexo1List.as_view()), name='list'),
    path('new', login_required(EvaluacionEntidadAnexo1Create.as_view()), name='new'),
    path('edit/<pk>', login_required(EvaluacionEntidadAnexo1Update.as_view()), name='edit'),
    path('delete/<pk>', login_required(EvaluacionEntidadAnexo1Delete.as_view()), name='delete'),
]

main/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from apps.reclamo.urls_api import router as router_reclamo
from setup.urls_api import router as router_setup

urlpatterns = [
                  path('', include('apps.index.url')),
                  path('accounts/', include('django.contrib.auth.urls')),
                  path('manager/', admin.site.urls),
                      #path('clearcache/', include('clearcache.urls')),


                  path('localizations/country/', include('apps.localizations.urls.country')),
                  path('localizations/department/', include('apps.localizations.urls.department')),
                  path('localizations/province/', include('apps.localizations.urls.province')),
                  path('localizations/district/', include('apps.localizations.urls.district')),

                  path('reclamo/', include('apps.reclamo.url')),
                  path('setup/usuario/', include('setup.urls.usuario')),
                  path('setup/entidad/', include('setup.urls.entidad')),
                  path('administrador/', include('apps.reclamo_administrador.url')),
                  path('evaluacion/', include('apps.evaluacion_entidad.urls')),
                  path('reportes/', include('apps.reportes.urls')),
                  path('trama-txt/', include('apps.trama_txt.urls')),

                  path('api/entidad/', include(router_reclamo.urls)),
                  path('api/setup/', include(router_setup.urls)),

              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL,
                                                                                           document_root=settings.MEDIA_ROOT)

apps/reclamo_administrador/models/evaluacion_anexo1.py
import os
import sys

from apps.reclamo.models.entidad_reclamo import MESES
from apps.util.anios import ANIOS
from setup.models.periodo import Periodo

if os.path.splitext(os.path.basename(sys.argv[0]))[0] == 'pydoc-script':
    pass

from django.db import models
from django.utils.translation import gettext_lazy as _

from apps.middlewares.request import AppRequestMiddleware
from apps.util.network import get_client_ip
from setup.models.entidad import Entidad
from setup.models.rubro_calificacion import RubroCalificacion
from setup.models.usuario import Usuario


class EvaluacionAnexo1(models.Model):
    entidad = models.ForeignKey(Entidad, on_delete=models.CASCADE)
    anio = models.PositiveIntegerField(_('Año'), choices=ANIOS)
    periodo = models.PositiveIntegerField(_('Periodo'), choices=MESES)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    created_ip = models.CharField(max_length=20, null=True, blank=True)
    updated_ip = models.CharField(max_length=20, null=True, blank=True)
    created_by = models.ForeignKey(Usuario, on_delete=models.CASCADE, related_name='created_by', null=True, blank=True)
    updated_by = models.ForeignKey(Usuario, on_delete=models.CASCADE, related_name='updated_by', null=True, blank=True)

    def __str__(self):
        return self.entidad.nombre

    def save(self, *args, **kwargs):
        current_request = AppRequestMiddleware.get_request()
        u = current_request.user

        try:
            if self._state.adding:
                self.created_by = u
                self.updated_by = u
                self.created_ip = get_client_ip(current_request)
                self.updated_ip = get_client_ip(current_request)
            else:
                self.updated_ip = get_client_ip(current_request)
                self.updated_by = u
        except KeyError:
            self.updated_ip = get_client_ip(current_request)
            self.updated_by = u
        super(EvaluacionAnexo1, self).save(*args, **kwargs)

    class Meta:
        unique_together = (("entidad", "anio", "periodo"),)
        verbose_name = _('Evaluación Anexo 1')
        verbose_name_plural = _('Evaluaciones Anexo 1')


class DetalleEvaluacionAnexo1(models.Model):
    evaluacion = models.ForeignKey(EvaluacionAnexo1, on_delete=models.CASCADE, null=True, blank=True)
    rubro = models.ForeignKey(RubroCalificacion, on_delete=models.CASCADE)
    calificacion = models.BooleanField(_('Calificación'), default=False)
    observacion = models.TextField(_('Observaciones'), max_length=700, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    created_ip = models.CharField(max_length=20, null=True, blank=True)
    updated_ip = models.CharField(max_length=20, null=True, blank=True)
    created_by = models.ForeignKey(Usuario, on_delete=models.CASCADE, related_name='detalle_created_by', null=True,
                                   blank=True)
    updated_by = models.ForeignKey(Usuario, on_delete=models.CASCADE, related_name='detalle_updated_by', null=True,
                                   blank=True)

    def __str__(self):
        return "%s -%s " % (self.calificacion, self.evaluacion_id)

    def save(self, *args, **kwargs):

        current_request = AppRequestMiddleware.get_request()
        u = current_request.user

        try:
            if self._state.adding:
                self.created_by = u
                self.updated_by = u
                self.created_ip = get_client_ip(current_request)
                self.updated_ip = get_client_ip(current_request)
            else:
                self.updated_ip = get_client_ip(current_request)
                self.updated_by = u
        except KeyError:
            self.updated_ip = get_client_ip(current_request)
            self.updated_by = u
        super(DetalleEvaluacionAnexo1, self).save(*args, **kwargs)

    class Meta:
        ordering = ['evaluacion', 'rubro__orden']
        verbose_name = _('Detalle evaluación Anexo 1')
        verbose_name_plural = _('Detalles Evaluacion Anexo 1')

apps/reclamo_administrador/forms/evaluacion_anexo1.py
from django import forms
from django.forms import DateInput, Textarea

from apps.reclamo_administrador.models.evaluacion_anexo1 import EvaluacionAnexo1, DetalleEvaluacionAnexo1
from apps.util.generic_filters import forms as gf
from setup.models.entidad import Entidad


class EvaluacionAnexo1Form(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        self.entidad_id = kwargs.pop('entidad_id')
        super().__init__(*args, **kwargs)
        # self.fields['entidad_reclamo'].choices = self.entidad_reclamo
        self.fields['entidad'].choices = Entidad.objects.filter(id=self.entidad_id).values_list(
            'id', 'id')[0:1]

    class Meta:
        model = EvaluacionAnexo1
        fields = '__all__'
        # fields = '__all__'
        widgets = {
            'fecha': DateInput(format='%Y-%m-%d')
        }


class EvaluacionAnexo1ListFilter(gf.FilteredForm):

    def get_order_by_choices(self):
        return []


class DetalleEvaluacionAnexo1Form(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        # self.evaluacion_id = kwargs.pop('evaluacion_id')
        super().__init__(*args, **kwargs)
        # self.fields['evaluacion'].choices = EvaluacionAnexo1.objects.filter(id=self.evaluacion_id).values_list(
        #     'id', 'id')[0:1]

        self.fields['evaluacion'].choices = EvaluacionAnexo1.objects.all().values_list('id', 'id')[:1]

    class Meta:
        model = DetalleEvaluacionAnexo1
        fields = '__all__'
        widgets = {
            'observacion': Textarea(attrs={'rows': '3'}),
        }

apps/evaluacion_entidad/views/evalucion_anexo1.py
from django.contrib import messages
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, UpdateView, DeleteView

from apps.reclamo_administrador.forms.evaluacion_anexo1 import EvaluacionAnexo1ListFilter, EvaluacionAnexo1Form, \
    DetalleEvaluacionAnexo1Form
from apps.reclamo_administrador.models.evaluacion_anexo1 import EvaluacionAnexo1, DetalleEvaluacionAnexo1
from apps.util.generic_filters.views import FilteredListView
from apps.util.valid_user_access_views import valid_access_view, permission_and_entidad, \
    valid_ipress_entidad_add, valid_ipress_anexo1_edit
from setup.models.entidad import Entidad
from setup.models.rubro_calificacion import RubroCalificacion


class EvaluacionEntidadAnexo1List(FilteredListView):
    model = EvaluacionAnexo1
    paginate_by = 20
    form_class = EvaluacionAnexo1ListFilter
    filter_fields = []
    search_fields = ['periodo', 'anio']
    default_order = '-id'
    template_name = 'evaluacion_entidad/evaluacionanexo1_list.html'

    @method_decorator(valid_access_view(permission_and_entidad, login_url='/validate'))
    def dispatch(self, *args, **kwargs):
        return super(EvaluacionEntidadAnexo1List, self).dispatch(*args, **kwargs)

    def get_context_data(self, **kwargs):
        entidad_id = self.request.session['entidad_id']
        title = "Evaluaciones"

        entidad = None

        if entidad_id:
            entidad = Entidad.objects.get(pk=entidad_id)
            title = "Todas las evaluaciones de la entidad: " + entidad.nombre

        return dict(
            super(EvaluacionEntidadAnexo1List, self).get_context_data(**kwargs), title=title, entidad=entidad)

    def get_queryset(self):
        queryset = super().get_queryset()

        entidad_id = self.request.session['entidad_id']

        if entidad_id:
            return queryset.filter(entidad_id=entidad_id).order_by('-id')
        else:
            return queryset.order_by('-id')


class EvaluacionEntidadAnexo1Create(CreateView):
    form_class = EvaluacionAnexo1Form
    model = EvaluacionAnexo1
    template_name = 'evaluacion_entidad/evaluacionanexo1_form.html'

    # success_url = reverse_lazy('reclamo:entidad-reclamo-list')

    @method_decorator(valid_access_view(valid_ipress_entidad_add, login_url='/validate'))
    def dispatch(self, *args, **kwargs):
        return super(EvaluacionEntidadAnexo1Create, self).dispatch(*args, **kwargs)

    def get_success_url(self):
        entidad_id = self.request.session['entidad_id']
        # return reverse_lazy('evaluacion-entidad:evaluacion-list', kwargs={'entidad_id': entidad_id})
        return reverse_lazy('evaluacion-entidad:list')

    def get_form_kwargs(self, *args, **kwargs):
        kwargs = super(EvaluacionEntidadAnexo1Create, self).get_form_kwargs(*args, **kwargs)
        entidad_id = self.request.session['entidad_id']
        kwargs['entidad_id'] = entidad_id
        return kwargs

    def form_valid(self, form):

        msg = "Evaluación agregada correctamente"
        messages.add_message(self.request, messages.SUCCESS, msg)

        self.object = form.save()

        entidad_id = self.request.session['entidad_id']
        self.object.entidad_id = entidad_id

        detalles = RubroCalificacion.objects.all()
        for index, detalle in enumerate(detalles):
            updated_data = self.request.POST.copy()
            updated_data.update({str(index) + '-evaluacion': self.object.id})
            detalle_form = DetalleEvaluacionAnexo1Form(updated_data, self.request.POST, prefix=str(index))
            if detalle_form.is_valid():
                detalle_form.save()
            else:
                print("Error al guardar el detalle")

        return super().form_valid(form)

    def get_context_data(self, **kwargs):

        entidad_id = self.request.session['entidad_id']
        entidad = Entidad.objects.get(pk=entidad_id)
        detalles = RubroCalificacion.objects.all()

        title = "Nueva Evaluación de la Entidad: " + entidad.nombre.upper()

        detalles_form = []

        for index, detalle in enumerate(detalles):
            detalle_form = DetalleEvaluacionAnexo1Form(initial={'rubro': detalle.id}, prefix=str(index))
            detalles_form.append(detalle_form)

        list_zip = zip(detalles, detalles_form)

        return dict(
            super(EvaluacionEntidadAnexo1Create, self).get_context_data(**kwargs), title=title, entidad=entidad,
            detalles_form=detalles_form, list_zip=list_zip)


class EvaluacionEntidadAnexo1Update(UpdateView):
    form_class = EvaluacionAnexo1Form
    model = EvaluacionAnexo1
    template_name = 'evaluacion_entidad/evaluacionanexo1_form.html'

    # success_url = reverse_lazy('reclamo:entidad-reclamo-list')

    @method_decorator(valid_access_view(valid_ipress_anexo1_edit, login_url='/validate'))
    def dispatch(self, *args, **kwargs):
        return super(EvaluacionEntidadAnexo1Update, self).dispatch(*args, **kwargs)

    def get_success_url(self):
        entidad_id = self.request.session['entidad_id']
        # return reverse_lazy('evaluacion-entidad:list', kwargs={'entidad_id': entidad_id})
        return reverse_lazy('evaluacion-entidad:list')

    def get_form_kwargs(self, *args, **kwargs):
        kwargs = super(EvaluacionEntidadAnexo1Update, self).get_form_kwargs(*args, **kwargs)
        entidad_id = self.request.session['entidad_id']
        kwargs['entidad_id'] = entidad_id
        return kwargs

    def form_valid(self, form):

        msg = "Evaluación editada correctamente"
        messages.add_message(self.request, messages.SUCCESS, msg)

        self.object = form.save()

        entidad_id = self.request.session['entidad_id']
        self.object.entidad_id = entidad_id

        detalles = RubroCalificacion.objects.all()
        evaluacion_id = self.kwargs['pk']

        for index, detalle in enumerate(detalles):

            updated_data = self.request.POST.copy()
            updated_data.update({str(index) + '-evaluacion': self.object.id})

            try:
                detalle_saved = DetalleEvaluacionAnexo1.objects.get(evaluacion_id=evaluacion_id, rubro_id=detalle.id)
                detalle_form = DetalleEvaluacionAnexo1Form(updated_data, self.request.POST, prefix=str(index),
                                                           instance=detalle_saved)
            except DetalleEvaluacionAnexo1.DoesNotExist:
                detalle_form = DetalleEvaluacionAnexo1Form(updated_data, self.request.POST, prefix=str(index))
            if detalle_form.is_valid():
                detalle_form.save()
            else:
                print("Error al guardar el detalle")

        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        entidad_id = self.request.session['entidad_id']
        entidad = Entidad.objects.get(pk=entidad_id)
        detalles = RubroCalificacion.objects.all()
        evaluacion_id = self.kwargs['pk']
        title = "Nueva Evaluación de la Entidad: " + entidad.nombre.upper()

        detalles_form = []

        for index, detalle in enumerate(detalles):
            try:
                detalle_saved = DetalleEvaluacionAnexo1.objects.get(evaluacion_id=evaluacion_id, rubro_id=detalle.id)
                detalle_form = DetalleEvaluacionAnexo1Form(instance=detalle_saved, prefix=str(index))
            except DetalleEvaluacionAnexo1.DoesNotExist:
                detalle_form = DetalleEvaluacionAnexo1Form(initial={'rubro': detalle.id}, prefix=str(index))
            detalles_form.append(detalle_form)

        list_zip = zip(detalles, detalles_form)

        return dict(
            super(EvaluacionEntidadAnexo1Update, self).get_context_data(**kwargs), title=title, entidad=entidad,
            detalles_form=detalles_form, list_zip=list_zip)


class EvaluacionEntidadAnexo1Delete(DeleteView):
    success_url = reverse_lazy('evaluacion-entidad:list')
    template_name = 'evaluacion_entidad/evaluacionanexo1_confirm_delete.html'
    model = EvaluacionAnexo1

    def delete(self, request, *args, **kwargs):
        msg = "Evaluación eliminada correctamente"
        messages.add_message(self.request, messages.ERROR, msg, extra_tags='danger')
        return super(EvaluacionEntidadAnexo1Delete, self).delete(request, *args, **kwargs)

apps/evaluacion_entidad/templates/evaluacion_entidad/evaluacionanexo1_confirm_delete.html
{% extends 'dashboard.html' %}

{% block  container %}


    <div class="app-content content">
        <div class="content-wrapper">
            <div class="content-header row">
                <div class="content-header-left col-md-6 col-12 mb-2">

                </div>
            </div>

            <div class="content-body">
                <div class="card text-white bg-danger mb-3" style="margin: 50px">
                    <div class="card-body text-center">
                        <form method="post">{% csrf_token %}
                            <h3 class="text-white"> Está seguro que desea eliminar la evaluación?</h3>
                            <button type="button" class="btn btn-default" id="cancel">Cancelar</button>
                            <button type="submit" class="btn btn-success">Confirmar</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>



{% endblock container %}

{% block static %}

    <script type="application/javascript">
        $('#cancel').click(function () {
            parent.history.back();
            return false;
        });
    </script>
{% endblock static %}

apps/evaluacion_entidad/templates/evaluacion_entidad/evaluacionanexo1_list.html
{% extends 'dashboard.html' %}
{% load paginator i18n %}
{% block  container %}

    <div class="app-content content">
        <div class="content-wrapper">
            <div class="content-header row">
                <div class="content-header-left col-md-6 col-12 mb-2">
                    <div class="row breadcrumbs-top">
                        <div class="breadcrumb-wrapper col-12">
                            <ol class="breadcrumb">
                                <li class="breadcrumb-item ">Evaluación</li>
                                <li class="breadcrumb-item active">{{ title }}</li>

                            </ol>
                        </div>
                    </div>
                </div>
                <div class="content-header-right col-md-6 col-12">
                    <div class=" float-md-right">
                        <div class="col-sm-12 col-lg-12 col-xl-12">

                            <a href="{% url 'evaluacion-entidad:new' %}"
                               class="btn btn-success btn-block"> <i class="la la-plus font-small-2"></i> Nueva
                                evaluación</a>

                        </div>
                    </div>
                </div>
            </div>

            <div class="content-body">
                <section id="patients-list">
                    <div class="row">
                        <div class="col-12">
                            <div class="card">
                                <div class="card-header">
                                    <h2 class="card-title">{{ title }}
                                        <strong class="text-primary">({{ page_obj.paginator.count }})</strong></h2>
                                </div>

                                <div class="card-body collapse show">
                                    <div class="row">
                                        <div class="col-md-2" hidden>
                                            {% include 'genericfilters/filter_list.html' %}
                                        </div>
                                        <div class="col-md-12">
                                            <div hidden>
                                                {% trans "Periodo, Año" as placeholder %}
                                                {% include 'genericfilters/query_filter.html' %}
                                            </div>
                                            <div class="table-responsive">
                                                <table class="table table-striped table-bordered ">
                                                    <thead>
                                                    <tr>
                                                        <th>#</th>
                                                        <th>Periodo</th>
                                                        <th>Año</th>
                                                        <th>OPC</th>
                                                    </tr>
                                                    </thead>
                                                    <tbody>
                                                    {% for object in object_list %}
                                                        <tr>
                                                            <th>{{ forloop.counter0|add:page_obj.start_index }}</th>
                                                            <td>{{ object.get_periodo_display }}</td>
                                                            <td>{{ object.anio }}</td>
                                                            <td class="text-center">
                                                                <a data-toggle="tooltip" data-placement="top"
                                                                   class="btn btn-warning btn-sm"
                                                                   title="editar"
                                                                        {#                                                                   class="btn btn-warning btn-sm"#}
                                                                   href="{% url  'evaluacion-entidad:edit' pk=object.id %}">
                                                                    <i class="ft ft-edit font-medium-2"></i></a>


                                                                <a href="{% url 'evaluacion-entidad:delete' object.id %}"
                                                                   class="btn btn-danger btn-sm"
                                                                   data-toggle="tooltip"
                                                                   data-placement="top"
                                                                   title="Eliminar Anexo 1"><i
                                                                        class="ft ft-delete font-medium-2  "> </i>
                                                                </a>

                                                            </td>
                                                        </tr>
                                                    {% endfor %}
                                                    </tbody>
                                                </table>
                                            </div>
                                            {% paginator %}
                                        </div>
                                    </div>
                                </div>


                            </div>
                        </div>
                    </div>
                </section>
            </div>
        </div>
    </div>

{% endblock container %}

{% block static %}

{% endblock static %}